export const techStackList: string[] = [
  "React",
  "TypeScript",
  "JavaScript",
  "HTML5",
  "CSS3",
  "Tailwind CSS",
  "Highcharts",
  "D3.js",
  "REST APIs",
  "GraphQL",
  "Apollo Client",
  "Redux",
  "Next.js",
  "Styled Components",
  "Node.js",
  "Git",
  "GitLab CI",
  "GitHub Copilot",
  "Cursor",
  "Windsurf",
  "Devin AI",
];
